{{- $secretName := printf "%s-user" (include "postgres-dev.fullname" .) }}

{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $postgresPassword := (randAlphaNum 15) | b64enc }}
{{- if $existingSecret }}
{{- $postgresPassword = (index $existingSecret.data "PGPASSWORD") }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "postgres-dev.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  PGUSER: {{ "postgres" | b64enc | quote }}
  PGPASSWORD: {{ $postgresPassword | quote }}
