apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-dev.fullname" . }}
  labels:
    {{- include "postgres-dev.labels" . | nindent 4 }}
spec:
  serviceName: "postgres-dev"
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-dev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-dev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-dev-user
              key: PGUSER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-dev-user
              key: PGPASSWORD
              optional: false
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-dev-pvc
          mountPath: /var/lib/postgresql/data
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: postgres-dev-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: postgis-storage
      resources:
        requests:
          storage: 20Gi
