apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-dev.fullname" . }}
  labels:
    {{- include "postgres-dev.labels" . | nindent 4 }}
spec:
  serviceName: "postgres-dev"
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-dev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-dev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "postgres-dev.fullname" . }}-user
              key: PGUSER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgres-dev.fullname" . }}-user
              key: PGPASSWORD
              optional: false
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - -e
              - |
                pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgresrun
          mountPath: /var/run/postgresql
        - name: data
          mountPath: /var/lib/postgresql/data
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: postgresrun
          emptyDir: 
            sizeLimit: 80Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
