# Default values for postgres-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # Alternative : postgis/postgis
  repository: postgres
  pullPolicy: IfNotPresent
  # default is appVersion in Chart.yaml
  # Alternative : "15-3.3" for postgis/postgis
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

persistence:
  #enabled: true
  storageClass: ""
  size: 8Gi

podSecurityContext:
  fsGroup: 999
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 999

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
